### ISSUE TITLE
Key values mismatch error

### ISSUE THREAD

**Issue by Gocht** [stephenmuss/django-ios-notifications#70]
I am trying to test notifications via console, and I am getting this error:

    Error: [('x509 certificate routines', 'X509_check_private_key', 'key values mismatch')]
I don't know what is this error related to. How can I fix this?

**Comment by stephenmuss** [comment]
It seems to be related to your APNS push certificate and private key setup. If it is not working I'd suggest following the steps at http://www.raywenderlich.com/3443/apple-push-notification-services-tutorial-part-12 to ensure you have set it up correctly.

Googling `X509_check_private_key "key values mismatch"` also turns up some useful results.

**Comment by Gocht** [comment]
I have succesfully registered the APNS using my keys, and I am using the hostname given [here](https://github.com/stephenmuss/django-ios-notifications), what could be the problem?

**Comment by stephenmuss** [comment]
As far as I can tell there is probably something not quite right with your certificate. Possibly there is something missing in the certificate chain.

If you follow the steps in the Ray Wenderlich tutorial I linked above you should have a certificate in the correct form. Otherwise you could try Google to find tools to help you debug the problem.

Unfortunately, it will be difficult for me to help you beyond those suggestions.
